# Generated by Django 4.0.2 on 2022-02-19 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('thresholds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
    ]
