# Generated by Django 4.0.2 on 2022-02-18 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinician_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clinician')),
            ],
        ),
    ]
