# Generated by Django 4.0.2 on 2022-02-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='auth_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='auth_login',
            field=models.BooleanField(default=False),
        ),
    ]
