# Generated by Django 4.0.2 on 2022-02-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date submitted'),
        ),
    ]
